### ISSUE TITLE
Cardano-Node 1.20.0 Compatible Version

### ISSUE THREAD

**Issue by vbonini** [vacuumlabs/adalite-backend-service#101]
Cardano Foundation release Cardano-Node 1.20.0 today. Can we get a compatible ADALITE version please? 
https://github.com/input-output-hk/cardano-node/releases/tag/1.20.0

**Comment by xdzurman** [comment]
We'll check on compatibility with IOHK's cardano-db-sync team whether the db-sync is compatible with the new node 1.20.0 and we'll let you know as soon as we know that. If it's compatible, we won't have to introduce any changes to the adalite code, if it's not compatible, we'll have to wait for a db-sync version and then incorporate any necessary changes.

**Comment by xdzurman** [comment]
@vbonini updates merged to develop
