### ISSUE TITLE
db-sync gets stuck when epoch changes

### ISSUE THREAD

**Issue by muratso** [vacuumlabs/adalite-backend-service#114]
Since the Allegra hard-fork every time the epoch changes we see db-sync getting stuck for 10~20 minutes till it starts syncing again. It doesn't throw any kind of error or anything, it just gets stuck.

The other components don't show any kind of errors too. Could this be on adalite-backend? It's being kinda hard to troubleshoot since Adalite is not spitting any logs when running on containers.

```
[db-sync-node:Info:58] [2021-01-15 21:44:48.16 UTC] insertShelleyBlock(Allegra): epoch 241, slot 19180797, block 5214208, hash 0693347fa180fe30c17c0637d352fceebad40e94d2e6076af61ec0aafbbce2ae
[db-sync-node:Info:61] [2021-01-15 21:46:14.26 UTC] getHistoryInterpreter: acquired
[db-sync-node:Info:58] [2021-01-15 21:46:16.46 UTC] insertShelleyBlock(Allegra): epoch 242, slot 19180800, block 5214209, hash 8275e35e1c79d6ae87fe07f5183c9bf7b28c74aaea7f09ad730c6406902f4ca2
[db-sync-node:Info:58] [2021-01-15 21:59:06.12 UTC] epochPluginInsertBlock: epoch 242
```

As you can see in the logs above, after the first block of 242 it got stuck for 13 minutes before it recovers and starts to sync again.
Do you guys have any clues on this?

**Comment by xdzurman** [comment]
Hey, this is db sync's fault. There's an ongoing issue
https://github.com/input-output-hk/cardano-db-sync/issues/478

**Comment by muratso** [comment]
Hey @xdzurman, my bad. I looked if there was an issue opened on their side but I completely missed that. Closing this issue. Thank you for responding promptly.

**Comment by xdzurman** [comment]
No problem :)
