### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#46]
Guys can you please point me to docs on api calls? What can I use here?

**Comment by refi93** [comment]
Sadly, there are no proper docs for the calls yet, but they can be picked up from the routes: 
https://github.com/vacuumlabs/adalite-backend-service/blob/refactor-docker-env/src/routes.js -> orginal routes from project-icarus-importer

https://github.com/vacuumlabs/adalite-backend-service/blob/develop/src/legacy-routes.js -> routes that emulate the api of cardanoexplorer.com with additional endpoints to get raw tx body and unspent outputs
