### ISSUE TITLE
Advice on importer

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#48]
I know that's not really your code, but maybe you can advice? The importer seems to load info in /wallet/mainnet directory, but the PG database seems to stay on size ~4Gb. Also the blockheight api call seems to be stucked on `1635981`

Logs look good (at least there are tones of them), showing that many processes are running. Can you advice some way of checking why there's no progress?

**Comment by refi93** [comment]
There is possibly some inconsistency, and you may not notice that at first sight from the logs - I'm not really sure if there is any meaningful message pointing to that, but a symptom of that is that it stops syncing. You can find out if you restart the importer service - it runs a consistency check and if it fails, it clearly displays it. You can fix it by restarting the importer with the `--recovery-mode` flag (it's an option available in the `manage_containers.sh` shellscript)

**Comment by ksemaev** [comment]
@refi93  TY very much, trying. Can you maybe advice on the size of /wallet directory on importer? It keeps writing the log to `/wallet/mainnet/log` and filling the volume

**Comment by refi93** [comment]
currently the wallet directory has 27.6 GB on our server, 25.5 of which is the /db directory and 2.1 is /logs
