### ISSUE TITLE
The reason for connecting to importer

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#50]
Sorry for me beeing slow, but can you please explain why adalite-backend needs a connection to importer api url? Isn't the PG connection enough?

What calls is it doing to importer? I don't fully understand the scheme, sorry :)

**Comment by refi93** [comment]
the adalite-backend-service just reads from the db and provides the API. The importer is basically a cardano node that is continuously syncing and pushing data (i.e. new transactions, blocks) to the posgtres DB.

**Comment by ksemaev** [comment]
Yep, I get it, but why do we provide importer's url ip:8200 for backend as a var? Does Backend connects to importer directly to get some information? 

It wasn't here - https://github.com/vacuumlabs/adalite-backend-service/blob/develop/docker-compose.yml#L13-L17
But you added it here: https://github.com/vacuumlabs/adalite-backend-service/pull/42/files#diff-072e81fe88d9b23fe00fc189279936a6R20

**Comment by refi93** [comment]
You need that connection in order to submit transactions
