### ISSUE TITLE
API call for blockheight

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#52]
Is there a way to understand if our node is synced (or where is it now)? 
Maybe there's an api call to cardano-sl-importer? Or an api call to backend-service?

Wasn't able to find myself, please advice

**Comment by refi93** [comment]
`/api/v2/bestBlock` provides the last block up to which the instance is synced and you can use it to cross-check it against another instance (the endpoint works even if the instance is unhealthy). That's one of the things healthcheck.js currently does underneath (or will do, once #51 is fixed, which should be soon, though it exposes only the end result (healthy/unhealthy)
