### ISSUE TITLE
Importer inode usage

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#53]
I know that you want to use something else than importer, and just wanted you to keep that in mind: currently `wallet` dir uses 25Gb, but also 5.5M inodes, so I have to keep it on 100Gb volume.

So if you could somehow minimize this number of tiny files, keeped in the fylesystem - that would be amazing.

**Comment by refi93** [comment]
I see - sadly we can't do much about it since this module is developed by IOHK: https://github.com/input-output-hk/project-icarus-importer Hopefully, the new service will be better but it won't be developed by us either

**Comment by ksemaev** [comment]
@refi93 can you tell where I can look for the progress on creating a new service?

**Comment by refi93** [comment]
@ksemaev The new service is being developed by Emurgo, but it isn't publicly released yet and sadly, we don't know when they will release it - it still isn't production-ready as far as we know. But they said they will release it on time and we will update our repo accordingly. I created an issue for that that you can watch: https://github.com/vacuumlabs/adalite-backend-service/issues/54

**Comment by ksemaev** [comment]
TY!
