### ISSUE TITLE
Advice on cardano-importer

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#55]
@refi93 Can you please tell which api calls can I use on this obsolete cardano importer? I want to add some monitoring while we use it, but I can't find any suitable apy call on port 8200 from here: https://cardanodocs.com/technical/wallet/api/

Please advice

**Comment by refi93** [comment]
If you mean what endpoints are exposed by the blockchain importer, then it seems that only the block count (/api/stats/blocksCount) and tx submission (/api/txs/signed) are available: https://github.com/input-output-hk/project-icarus-importer/blob/248c7880c25e641c78a620e3a3f97149e98eeb93/blockchain-importer/src/Pos/BlockchainImporter/Web/Api.hs - I think the blockchain importer is not running a full wallet instance, so the docs you linked do not apply.

**Comment by ksemaev** [comment]
TY very much!
