### ISSUE TITLE
Only bestblock api call is working 

### ISSUE THREAD

**Issue by ksemaev** [vacuumlabs/adalite-backend-service#56]
There are multiple calls here: https://github.com/vacuumlabs/adalite-backend-service/blob/develop/src/routes.js#L194-L230

But all POST ones return {"code":"Internal","message":"The instance is unhealthy"}
Can you advice on how to fix it please?

**Comment by refi93** [comment]
is the instance syncing properly? Is the bestBlock in par with the current actual block number in Cardano? How the healtcheck works is explained in this issue: https://github.com/vacuumlabs/adalite-backend-service/issues/47

**Comment by ksemaev** [comment]
Adalite is fully synced, as my api/v2/bestBlock equals the value from https://explorer2.adalite.io/api/v2/bestBlock

Still it reports unhealthy. Maybe it's https://github.com/vacuumlabs/adalite-backend-service/issues/51 ? Do we have an update for this?

**Comment by refi93** [comment]
@ksemaev it's very likely, sorry for the delay. Try pulling #57 Did it help?

**Comment by ksemaev** [comment]
Buuilding from `6f32e1da621b35b9f5876d1b22a68a8440ee132b` did the trick TY! All the calls work now
