### ISSUE TITLE
inconsistency detected

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/adalite-backend-service#64]
Restarting container I got this error on the importer:

> Inconsistency detected between Rocks and Postgres DBs, start using --recovery-mode flag

What does it means? how to fix it?

**Comment by refi93** [comment]
You can use the `start-recovery` action of the `manage_containers.sh` script to run the importer in recovery mode, see: https://github.com/vacuumlabs/adalite-backend-service/blob/develop/docker/manage_containers.sh

And here it is mentioned in the readme: https://github.com/vacuumlabs/adalite-backend-service#production-environment

Once the container is done with the recovery I would recommend restarting it in "normal" mode as we were experiencing worse stability of it when running long-term in recovery mode.

Sometimes after restarting it in normal mode which executes a consistency check in the beginning it may report inconsistencies even after running the container in recovery mode - then we were able to restore it to consistent state only by completely deleting the state of the container and launching it from scratch.
