### ISSUE TITLE
Deployment issues

### ISSUE THREAD

**Issue by yzkun001** [vacuumlabs/adalite-backend-service#91]
I want to deploy an adalite-backend-service on the server, what should I do? What is the process？
Do I still need to deploy cardano-node？

**Comment by xdzurman** [comment]
@1044740162 Hello, please follow the instructions stated in the [top level README](https://github.com/vacuumlabs/adalite-backend-service/blob/develop/README.md) for environment of your choice. If you encounter any issues, don't hesitate to ping us. Yes, it is necessary to start cardano-node, as well as other components - cardano-db-sync, cardano-rest, postgres easily by the docker compose.

**Comment by yzkun001** [comment]
Ok thank you very much
