### ISSUE TITLE
request  api error

### ISSUE THREAD

**Issue by IMKAIER** [vacuumlabs/adalite-backend-service#92]
BLOCKCHAIN_EXPLORER_UR /api/bulk/addresses/summary' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by MichalPetro** [comment]
Please refer to my answer here and state the reason for your interest in our technology before we provide any technical support to you. https://github.com/vacuumlabs/adalite/issues/697#issuecomment-674779143

**Comment by MichalPetro** [comment]
No, response, unfortunately, we cant help you due way too many phishing websites popping up
