### ISSUE TITLE
get accountDbId given an address

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/adalite-backend-service#94]
Is there an API to get the `accountDbId` given an `address`?

**Comment by xdzurman** [comment]
@roccomuso Here: https://github.com/vacuumlabs/adalite-backend-service/blob/shelley-hard-fork/src/db-api.js#L260 in the db-api. "account" represents staking address everywhere, this comes from the naming in the ITN era, I plan to rename it though to avoid confusion. It does not have an endpoint however, do you need it as an endpoint?

**Comment by roccomuso** [comment]
Yeah I saw that, but it's not exposed as a REST api, that would be great

**Comment by xdzurman** [comment]
Sorry, what would you need it for?

**Comment by roccomuso** [comment]
No need for it anymore. The other API are enough
