### ISSUE TITLE
[question] accountInfo rewards

### ISSUE THREAD

**Issue by roccomuso** [vacuumlabs/adalite-backend-service#97]
I saw that `api/account/info/:stakingAddress` returns something like:

```json
{
    "delegation": {
        ...
    },
    "hasStakingKey": true,
    "rewards": 0
}
```

Is `hasStakingKey` true even if wallet unstaked? is it like a field stating the staking key has been revealed?
Are those the total collected `rewards` or pending rewards?

**Comment by xdzurman** [comment]
In order to stake, you have to register your staking address with a deposit. You can deregister it later to retrieve the deposit. hasStakingKey means whether the address is registered or not. 

Pending rewards.
